from aioredis change to redis
pgjones/quart-rate-limiter pull request #4
Opened 2022-12-22 18:03 UTC by iasukas

aioredis is no longer maintained, so switch to redis

[https://github.com/redis/redis-py/releases/tag/v4.2.0rc1](https://github.com/redis/redis-py/releases/tag/v4.2.0rc1)

[PR](https://github.com/aio-libs/aioredis-py/issues/1443)

2022-12-22 19:11 UTC, pgjones requested changes
Thanks! A couple of changes are required, then I can merge.

2022-12-22 19:11 UTC, pgjones commented on pyproject.toml
> +redis = ">=4.4.0"
This still needs to be optional

2022-12-22 19:11 UTC, pgjones commented on CHANGELOG.rst
> +* Support redis >= 4.4.0.
This line can't be changed (0.6.0 has been released), a new changelog entry needs to be created instead.

2022-12-23 02:10 UTC, iasukas commented
Thanks! I have corrected the mistake you mentioned, please check again to see if there are other problems

2022-12-23 09:18 UTC, pgjones commented on pyproject.toml
> +redis = ">=4.4.0"
as in, 
```
redis = { version = ">=4.4.0", optional = true }
```
with the aioredis line removed.

2022-12-23 09:40 UTC, iasukas commented on pyproject.toml
> +redis = ">=4.4.0"
OK

2022-12-23 18:11 UTC, merged